[phases.setup]
nixPkgs = ["rustc", "cargo", "gcc", "pkg-config", "openssl"]

[phases.build]
cmds = ["cargo build --release && mkdir -p bin && cp target/release/casaora-backend-rs bin/"]

[start]
cmd = "./bin/casaora-backend-rs"
